---
title: "Beck Paper1 PCA DryAlmond and Pistachio"
author: "Maritza Romero"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import Data: 
####  (3 Reps each of Dry Pistacio and Dry Almond for Days 0,1,3,7)
```{r}
```


```{r}
dat1 <- read.csv("DataFormattedV2.csv", header=T, row.names=1,) 
dat1[1:6,1:4]  # look at the first few rows
```

### Replace zeroes with a small value:
```{r}
# This function will find the minimum value greater than zero 
# and divide that value by two
replacezero = function(x) "[<-"(x, !x | is.na(x), min(x[x > 0], na.rm = TRUE) / 2)

# Apply function across rows
dat2 <- as.data.frame(t(apply(dat1, 1, replacezero)))
dat2[1:6,1:4]  # look at the first few rows
```
```{r}
# Log transform the data (base 2 log)
logdata <- log(dat2, 2)

# Function for pareto scaling
paretoscale <- function(z) {
  rowmean <- apply(z, 1, mean) # row means
  rowsd <- apply(z, 1, sd)  # row standard deviation
  rowsqrtsd <- sqrt(rowsd) # sqrt of sd
  rv <- sweep(z, 1, rowmean,"-")  # mean center
  rv <- sweep(rv, 1, rowsqrtsd, "/")  # dividing by sqrtsd
  return(rv)
}

# Pareto scale log transformed data
logdata.pareto <- paretoscale(logdata)

# Run PCA (note use of "t" to transpose matrix)
pca <- prcomp(t(logdata.pareto), center=F, scale=F)
```

```{r}
# Create a container called "results" for PCA results
results <- summary(pca)

results$importance  # summary table of explained variance
results$x           # scores matrix
results$rotation    # loadings matrix

```

```{r}
# Make a simple scree plot
plot(results$importance[2,1:10], type="b", 
     main="Proportion of Explained Variance",
     xlab="PC", ylab="Proportion of Variance")

# Plot the cumulative proportion of variance
plot(results$importance[3,1:10], type="b", 
     main="Cumulative Proportion of Variance",
     xlab="PC", ylab="Proportion of Variance")

# Make a simple scores plot
plot(pca$x[,1], pca$x[,2], type='p', cex=0, pch=20, 
     main="Scores Plot", xlab="PC1", ylab="PC2")

# add text labels to data points
text(pca$x[,1], pca$x[,2], labels=rownames(pca$x), cex=1.0)
abline(h=0, v=0, col="red")
```

```{r}
# Make a simple loadings plot (variance among variables)
plot(pca$rotation[,1], pca$rotation[,2], type='p', cex=0.5, pch=20, 
     main="Loadings Plot", xlab="PC1", ylab="PC2")

# add text labels for data points
text(pca$rotation[,1], pca$rotation[,2], labels=rownames(pca$rotation), cex=1.0)
abline(h=0, v=0, col="red")

# Extract PCA results into data frames

scree.data <- as.data.frame(results$importance)
score.data <- as.data.frame(results$x)
loadings.data <- as.data.frame(results$rotation)

# Save PCA results to file (we'll use later)
write.csv(scree.data, "pca_scree.csv")
write.csv(score.data, "pca_scores.csv")
write.csv(loadings.data, "pca_loadings.csv")

# Find important variables (Loadings)

plot(loadings.data$PC1, loadings.data$PC2)
abline(v=0.09, col="red")
abline(v=-0.09, col="red")
abline(h=0.09, col="red")
abline(h=-0.09, col="red")

# Make a new data frame with PC1, PC2, and PC3 loadings
loadings.PC1.PC2 <- loadings.data[,1:3]
loadings.PC1.PC2[1:6,1:3]  # look at the first few rows

# subset significant loadings
loadings.sig <- subset(loadings.PC1.PC2,
                       PC1 > 0.09 | PC1 < -0.09 |
                         PC2 > 0.09 | PC2 < -0.09)

# sanity check - plot the results
plot(loadings.sig$PC1, loadings.sig$PC2)

# Use the "ifelse" function to mark high loadings

# PC1 loadings
loadings.sig$pc1.change <-
  ifelse(loadings.sig$PC1 > 0.09,"UP",
         ifelse(loadings.sig$PC1 < -0.09,"DOWN",
                "none"))

# PC2 loadings
loadings.sig$pc2.change <-
  ifelse(loadings.sig$PC2 > 0.09,"UP",
         ifelse(loadings.sig$PC2 < -0.09,"DOWN",
                "none"))

# Number of signficant PC1 loadings
length(which(loadings.sig$pc1.change=="UP"))
length(which(loadings.sig$pc1.change=="DOWN"))
length(which(loadings.sig$pc1.change=="none"))

# Number of signficant PC2 loadings
length(which(loadings.sig$pc2.change=="UP"))
length(which(loadings.sig$pc2.change=="DOWN"))
length(which(loadings.sig$pc2.change=="none"))

# Write significant loadings to file for later use.
write.csv(loadings.sig, "sig_loadings.csv")

# Merge significant PC1 and PC2 loadings with raw data
# Note: use missing values corrected data
pca.sig.vars <- merge(dat2, loadings.sig, by="row.names")


# use the "arrange" function in the plyr package to order
library(plyr)
pca.sig.vars <- arrange(pca.sig.vars, pc1.change, pc2.change)

# Re-assign row names and delete "Row.names" column
row.names(pca.sig.vars) <- pca.sig.vars$Row.names
pca.sig.vars$Row.names <- NULL

# Write the results to file for later use.
write.csv(pca.sig.vars, "dat_sig_loadings.csv")

```

###Plots with Ellipses
```{r}
# import scores matrix
data <- read.csv("pca_scores.csv", header=T)

# subset to include only PC1 to PC3 scores
data <- data[, c(1:4)]

# look at first few rows
data[1:6,1:4]

# Get variance percentages for first 3 PC's
screedat <- read.csv("pca_scree.csv", header=T)
var1 <- round(screedat[2,2:4] * 100, 1)

# Change "X" column to "Sample"
colnames(data)[colnames(data)=="X"] <- "Sample"

# Add Group label to the data frame
Group <- c(rep("DryPistachio", 12),
           rep("DryAlmond", 12))
         

data <- cbind(data, Group)

# install ggplot2 (can skip if already installed)
#install.packages("ggplot2")

# load ggplot2
library(ggplot2)

# Make custom theme for ggplot
my.theme <- theme(axis.text = element_text(colour="black", size=15),
                  text = element_text(size=16),
                  title = element_text(size=18, face="bold", vjust=2),
                  panel.background = element_rect(fill = 'gray99',
                                                  colour = "black", 
                                                  size=0.5),
                  axis.title.x=  element_text(vjust=-0.45),
                  axis.title.y = element_text(vjust=1.2),
                  axis.ticks = element_line(colour="black"),
                  axis.line = element_line(),
                  panel.grid.major = element_line(colour = "gray40", linetype="dotted"),
                  panel.grid.minor = element_line(colour = "gray40", linetype="dashed"),
                  legend.justification=c(1,1),
                  legend.position=c(1,1),
                  legend.title=element_blank(),
                  legend.text = element_text(size = 14))

# check variances for PC1 and PC2
var1

# Calculate 95% ellipse values for PC1,PC2
library(ellipse)

centroids <- aggregate(cbind(PC1,PC2)~Group,data,mean)
#---------this section did not work remove 
# conf.rgn1  <- do.call(rbind,lapply(unique(data$Group),function(t)# no function (T)
#   data.frame(Group=as.character(t),
#              ellipse(cov(data[data$Group==t,2:3]),
#                      centre=as.matrix(centroids[t,2:3]),
#                      level=0.95),
#              stringsAsFactors=FALSE)))

# make plot for PC1 vs. PC2
g1 <-
  ggplot(data, aes(PC1, PC2)) +
  geom_hline(yintercept = 0, colour = "gray50") +
  geom_vline(xintercept = 0, colour = "gray50") +
  # geom_polygon(data=conf.rgn1,  # this did not work
  #              aes(fill=Group), colour="black", alpha = 0.2, 
  #              linetype="blank", show.legend=FALSE) +
  geom_point(aes(shape=Group, bg=Group), colour="black", size=4.5) +
  geom_text(aes(label=data$Sample), colour="black", 
            size=4, hjust=-0.25, vjust=1) +
  #this is the correct way to apply geom polygon in line 88
  stat_ellipse(geom = "polygon",
               aes(fill = Group), 
               alpha = 0.25)+
  
  
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values=c(21,22,23,24)) +
  ggtitle("PCA Scores Plot") +
  xlab("PC 1 (87.9%)") + #from var1 above
  ylab("PC 2 (4.7%)") +
  my.theme +
  theme(legend.position=c(0.25,0.25))
  
# draw scores plot
g1

# save as png file
png(file="scores.plot.png", height=2400, width=2800, res=350)
g1
dev.off()

######################
# Loadings plot
######################

# Import loadings matrix
loadings <- read.csv("pca_loadings.csv", header=T)

# subset to include only PC1 to PC3 loadings
loadings <- loadings[, c(1:4)]

# look at first few rows
loadings[1:6,1:4]

# Change "X" column to "Variable"
colnames(loadings)[colnames(loadings)=="X"] <- "Variable"

# make a quick loadings plot
plot(loadings$PC1, loadings$PC2)

# add lines for cutoff values
abline(v=0.09, col="red")
abline(v=-0.09, col="red")
abline(h=0.09, col="red")
abline(h=-0.09, col="red")

# Create new column based on PC1 loadings
loadings$pc1.change <-
  ifelse(loadings$PC1 > 0.09,"UP",
         ifelse(loadings$PC1 < -0.09,"DOWN",
                "zeit"))

# Create new column based on PC2 loadings
loadings$pc2.change <-
  ifelse(loadings$PC2 > 0.09,"UP",
         ifelse(loadings$PC2 < -0.09,"DOWN",
                "zeit"))

# Create label column for PC1 loadings
loadings$pc1.label <-
  ifelse(loadings$PC1 > 0.09, as.character(loadings$Variable),
         ifelse(loadings$PC1 < -0.09, as.character(loadings$Variable),
                "null"))

# Create label column for PC2 loadings
loadings$pc2.label <-
  ifelse(loadings$PC2 > 0.09, as.character(loadings$Variable),
         ifelse(loadings$PC2 < -0.09, as.character(loadings$Variable),
                "null"))

# subset significant loadings
loadings.sig <- subset(loadings,
                       PC1 > 0.09 | PC1 < -0.09 |
                         PC2 > 0.09 | PC2 < -0.09)

library(plyr)

# use the "arrange" function in the plyr package to sort
loadings.sig <- arrange(loadings.sig, pc1.change, pc2.change)

# Write the results to file 
write.csv(loadings.sig, "significant_loadings.csv", row.names=F)

# make loadings plot
g2 <-
  ggplot(loadings, aes(PC1, PC2)) +
  geom_hline(yintercept = 0, colour = "gray40") +
  geom_vline(xintercept = 0, colour = "gray40") +
  geom_point(size=2.5, pch=21, color="gray20", bg="khaki1") +
  stat_ellipse(level=0.15, colour="gray40", linetype="dashed", type="euclid") +
  geom_point(data=subset(loadings, pc1.change=="UP"),
             size=4, pch=21, color="black", bg="blue") +
  geom_point(data=subset(loadings, pc1.change=="DOWN"),
             size=4, pch=22, color="black", bg="orange") +
  geom_point(data=subset(loadings, pc2.change=="UP"),
             size=4, pch=23, color="black", bg="green") +
  geom_point(data=subset(loadings, pc2.change=="DOWN"),
             size=4, pch=24, color="black", bg="red") +
  scale_x_continuous(limits = c(-0.18, 0.16)) +
  scale_y_continuous(limits = c(-0.16, 0.16)) +
  ggtitle("PCA Loadings Plot") +
  my.theme

# draw loadings plot
g2

# add text annotations using the grid package
library(grid)

PC1.pos <- grobTree(textGrob("Positively \n correlated \n with PC1",
                             x=0.82, y=0.22, gp=gpar(col="blue", fontsize=14, fontface="bold")))
PC1.neg <- grobTree(textGrob("Negatively \n correlated \n with PC1",
                             x=0.15, y=0.7, gp=gpar(col="orange", fontsize=14, fontface="bold")))
PC2.pos <- grobTree(textGrob("Positively \n correlated \n with PC2",
                             x=0.63, y=0.88, gp=gpar(col="green", fontsize=14, fontface="bold")))
PC2.neg <- grobTree(textGrob("Negatively \n correlated \n with PC2",
                             x=0.17, y=0.1, gp=gpar(col="red", fontsize=14, fontface="bold")))

g2a <-
  g2 +
  annotation_custom(PC1.pos) +
  annotation_custom(PC1.neg) +
  annotation_custom(PC2.pos) +
  annotation_custom(PC2.neg)

g2a

# save as png file
png(file="loadings.plot.png", height=2400, width=2800, res=350)
g2a
dev.off()

```

